"""empty message

Revision ID: 0ef995027358
Revises: 76d8be9736aa
Create Date: 2024-04-05 12:16:19.020836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef995027358'
down_revision = '76d8be9736aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_360p_done', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_480p_done', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_720p_done', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_1080p_done', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('is_1080p_done')
        batch_op.drop_column('is_720p_done')
        batch_op.drop_column('is_480p_done')
        batch_op.drop_column('is_360p_done')

    # ### end Alembic commands ###
