"""empty message

Revision ID: 19111cd77480
Revises: a16cffe274e3
Create Date: 2024-02-15 12:02:12.406634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19111cd77480'
down_revision = 'a16cffe274e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chunks_uploaded', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('resource_chunks', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('chunks_uploaded')

    # ### end Alembic commands ###
