"""empty message

Revision ID: 521f951f2f75
Revises: 19111cd77480
Create Date: 2024-02-15 16:43:30.362004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521f951f2f75'
down_revision = '19111cd77480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('directory', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('directory')
        batch_op.drop_column('type')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
