"""empty message

Revision ID: 645ea5b1bab5
Revises: 521f951f2f75
Create Date: 2024-02-21 13:21:09.043240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645ea5b1bab5'
down_revision = '521f951f2f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('company')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
