"""empty message

Revision ID: 7761877df5fb
Revises: ac3d31f5072b
Create Date: 2024-09-24 17:28:35.863227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7761877df5fb'
down_revision = 'ac3d31f5072b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('need_processing', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('need_processing')

    # ### end Alembic commands ###
