"""empty message

Revision ID: a16cffe274e3
Revises: 
Create Date: 2024-02-15 02:27:46.863044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16cffe274e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('resource_chunks',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('data_key', sa.String(length=1000), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_chunks')
    op.drop_table('resource')
    # ### end Alembic commands ###
