"""empty message

Revision ID: c6d833c99399
Revises: e8fa06bd8f5a
Create Date: 2024-04-18 21:49:33.731038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d833c99399'
down_revision = 'e8fa06bd8f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_chunks', schema=None) as batch_op:
        batch_op.drop_column('tag')

    # ### end Alembic commands ###
