"""empty message

Revision ID: e8fa06bd8f5a
Revises: 87fc3024d48c
Create Date: 2024-04-18 21:17:30.655262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fa06bd8f5a'
down_revision = '87fc3024d48c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_id', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('upload_id')

    # ### end Alembic commands ###
